# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
      sonata.user.admin.user.class: Gaz\UserBundle\Admin\Model\UserAdmin

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
